### ISSUE TITLE
Program not launching

### ISSUE THREAD

**Issue by keichitokuna** [silverslither/cczdecrypt#1]
Hello,

I am on windows 10.
I installed GCC.
I downloaded libdeflate and copy cczdecrypt.exe inside the folder.
![Capture d’écran 2024-01-07 à 02 24 27](https://github.com/silverslither/cczdecrypt/assets/13786607/f32d7505-6ced-46a5-a866-869defb132c0)

But when i try to run cczdecrypt.exe i only see a cmd prompt flashing.

Can you provide me some assitance ?

Thanks

**Comment by silverslither** [comment]
cczdecrypt is invoked from the command-line the same way you invoked gcc (which isn't required for running the program anyway, it's only for compiling from source).

To use the program you'll need to pass the encryption key to the program (run ```cczdecrypt --help``` for more info).

By the way, I'm not sure which tutorial you followed but your gcc is 7+ years out of date. The latest version is ```13.2```, which you can get from the MSYS2 project's MinGW.

**Comment by keichitokuna** [comment]
Hello,

Thank you for your quick reply.
With MiniGW, i can now use cczdecrypt --help.

I just need to ask my coworkers for the key, miss that part...

Thanks again !

K.
